#\u9ED8\u8BA4\u7684\u73AF\u5883\u914D\u7F6E
spring:
  #\u5B9A\u4E49\u4F7F\u7528\u7684\u73AF\u5883\u914D\u7F6E\u6587\u4EF6
  profiles:
    active: dev
  #\u5B9A\u4E49\u6570\u636E\u6E90
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/book?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://rm-2zeedrx4ao895w03jko.mysql.rds.aliyuncs.com:3306/gd_subdb_1ehb1rp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    #    username: SeaChen
    #    password: 3389
    username: kaifa
    password: Goodo123
  thymeleaf:
    cache: false
    check-template-location: true
    #\u8BE5\u6A21\u677F\u9ED8\u8BA4HTML\u6587\u4EF6\u53EF\u5220\u9664
    suffix: .html
  mvc:
    view:
      suffix: .html
# MyBatis\u914D\u7F6E
mybatis:
  # \u641C\u7D22\u6307\u5B9A\u5305\u522B\u540D
  typeAliasesPackage: com.book.entity
  # \u914D\u7F6Emapper\u7684\u626B\u63CF\uFF0C\u627E\u5230\u6240\u6709\u7684mapper.xml\u6620\u5C04\u6587\u4EF6
  mapperLocations: classpath*:mapper/*Dao.xml
